
import type { Metadata } from "next";
import { Raleway, Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const noto_serif_bengali = Noto_Serif_Bengali({
  variable: "--font-noto-seif-bengali",
  subsets: ["bengali"]
})

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "বইয়ের বিদ্বান",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable}, ${noto_serif_bengali.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>

      </body>
    </html>
  );
}
